// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFG3_mN46jnjDqXy_TRhKHKRwOGBFkGNU',
    appId: '1:121116557971:web:904818ae76ed7658198366',
    messagingSenderId: '121116557971',
    projectId: 'quizz-ce4f8',
    authDomain: 'quizz-ce4f8.firebaseapp.com',
    storageBucket: 'quizz-ce4f8.appspot.com',
    measurementId: 'G-3QK9RJ9B1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNOyIMgAkNAe6pWlykOBK0xSrToGuntqQ',
    appId: '1:121116557971:android:090eec6c263ea4af198366',
    messagingSenderId: '121116557971',
    projectId: 'quizz-ce4f8',
    storageBucket: 'quizz-ce4f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK7s4BM8SRrnkm_sORoUqDx3CDt5uH4Uc',
    appId: '1:121116557971:ios:838b6f617f0782e5198366',
    messagingSenderId: '121116557971',
    projectId: 'quizz-ce4f8',
    storageBucket: 'quizz-ce4f8.appspot.com',
    iosClientId: '121116557971-lhclt1br39rqnrn13v7rtbge2fm4tfhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.Quizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK7s4BM8SRrnkm_sORoUqDx3CDt5uH4Uc',
    appId: '1:121116557971:ios:838b6f617f0782e5198366',
    messagingSenderId: '121116557971',
    projectId: 'quizz-ce4f8',
    storageBucket: 'quizz-ce4f8.appspot.com',
    iosClientId: '121116557971-lhclt1br39rqnrn13v7rtbge2fm4tfhu.apps.googleusercontent.com',
    iosBundleId: 'com.example.Quizz',
  );
}
