// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy-l8pUtU_GXp-wJiZpOqJc7Y_3sSTwsk',
    appId: '1:351413438688:web:d47cfb55cd4f4e8d80e885',
    messagingSenderId: '351413438688',
    projectId: 'quizz-a0bb3',
    authDomain: 'quizz-a0bb3.firebaseapp.com',
    storageBucket: 'quizz-a0bb3.appspot.com',
    measurementId: 'G-2MTFJ1D0FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHyUzOnsQJwQtmGKSgetqKtivc0zVVnhk',
    appId: '1:351413438688:android:7c2736403d419af080e885',
    messagingSenderId: '351413438688',
    projectId: 'quizz-a0bb3',
    storageBucket: 'quizz-a0bb3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJBZLP2O9I1_Va3PT58TXuaXViepsU1VQ',
    appId: '1:351413438688:ios:204d3ff34069f82780e885',
    messagingSenderId: '351413438688',
    projectId: 'quizz-a0bb3',
    storageBucket: 'quizz-a0bb3.appspot.com',
    iosClientId: '351413438688-3upva5jm7nb1ioo41ippja961q5brl1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.Quizz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJBZLP2O9I1_Va3PT58TXuaXViepsU1VQ',
    appId: '1:351413438688:ios:204d3ff34069f82780e885',
    messagingSenderId: '351413438688',
    projectId: 'quizz-a0bb3',
    storageBucket: 'quizz-a0bb3.appspot.com',
    iosClientId: '351413438688-3upva5jm7nb1ioo41ippja961q5brl1s.apps.googleusercontent.com',
    iosBundleId: 'com.example.Quizz',
  );
}
